# Generated by Django 4.2 on 2023-09-29 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30, verbose_name='Father Name')),
                ('g_fund_no', models.CharField(max_length=15, verbose_name='GP Fund Number')),
                ('salary', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=17)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/teacher/profile', verbose_name='Profile Image')),
                ('address', models.TextField(max_length=200)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('personal_no', models.CharField(max_length=10, unique=True, verbose_name='Personal Number')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('0', 'FeMale')], max_length=1)),
                ('isInPrimarySchool', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True)),
                ('dateOfTakingOverChargeInPresentSchool', models.DateField(default=django.utils.timezone.now, verbose_name='Date of taking over charge in present school')),
                ('dateOfTakingOverChargeOnPresentPost', models.DateField(default=django.utils.timezone.now, verbose_name='Date of taking over charge on present post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.post')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fromSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromTransfers', to='schools.school', verbose_name='From School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='staff.teacher', verbose_name='Teacher')),
                ('toSchool', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toTransfers', to='schools.school', verbose_name='To School')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFirstAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfFirstAppointment', models.DateField(verbose_name='Date of first appointment')),
                ('appointmentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAppointments', to='core.post', verbose_name='Post')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherFirstAppointment', to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fromPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPromotions', to='core.post', verbose_name='From Post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='staff.teacher', verbose_name='Teacher')),
                ('toPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toPromotionss', to='core.post', verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11, unique=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='New Professional Qualification')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proffqualification', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Professional Qualification',
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeacherMonthlyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TMEs', to='core.post')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TME', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TMEs', to='staff.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAccadQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='New Academic Qualification')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accadqualification', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Accadmic Qualification',
                'unique_together': {('teacher', 'name')},
            },
        ),
    ]
