# Generated by Django 4.2 on 2023-09-29 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherMonthlyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=10)),
                ('dateOfTakingOverChargeOnPresentPost', models.DateField(default=django.utils.timezone.now, verbose_name='date Of Taking Over Charge On Present Post')),
                ('dateOfTakingOverChargeInPresentSchool', models.DateField(default=django.utils.timezone.now, verbose_name='date Of Taking Over Charge In Present School')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachersRecords', to='monthlyEntry.monthlyrecord')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherRecords', to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(choices=[('1', 'Kachi'), ('2', 'Pki'), ('3', '2nd'), ('4', '3rd'), ('5', '4th'), ('6', '5th')], max_length=1)),
                ('boys', models.CharField(max_length=3)),
                ('girls', models.CharField(max_length=3)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentStrength', to='monthlyEntry.monthlyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAvalibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanctioned', models.CharField(max_length=1)),
                ('filled', models.CharField(max_length=1)),
                ('surplus', models.CharField(max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='monthlyEntry.monthlyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfItems', models.CharField(max_length=5, verbose_name='No of Items')),
                ('required', models.CharField(max_length=5)),
                ('surplus', models.CharField(max_length=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock_item')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='monthlyEntry.monthlyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfConstruction', models.DateField(verbose_name='Year of Construction')),
                ('waterSource', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Water Source')),
                ('boundryWall', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Boundry Wall')),
                ('playGroud', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Play Ground')),
                ('noOfToilets', models.CharField(max_length=2, verbose_name='No of Toilets')),
                ('scienceLaboratory', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Science Laboratory')),
                ('computerLaboratory', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Computer Laboratory')),
                ('coverdArea', models.CharField(max_length=10, verbose_name='Coverd')),
                ('uncoverdArea', models.CharField(max_length=10, verbose_name='UnCoverd')),
                ('noOfClassRooms', models.CharField(max_length=2, verbose_name='No of Class Rooms')),
                ('noOfOtherRooms', models.CharField(max_length=2, verbose_name='No of Other Rooms')),
                ('fruitTrees', models.CharField(max_length=2, verbose_name='Fruit Trees')),
                ('shadyTrees', models.CharField(max_length=2, verbose_name='Shady Trees')),
                ('internalElectrification', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Internal Electrification')),
                ('electricSuply', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Electric Suply')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='monthlyEntry.monthlyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PTC_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionDate', models.DateField(verbose_name='PTC Election Date')),
                ('estiblishDate', models.DateField(verbose_name='PTC Establish Date')),
                ('areaCode', models.PositiveBigIntegerField(verbose_name='Branc/Area/Code No')),
                ('accountNo', models.CharField(max_length=10, verbose_name='Account No')),
                ('lastYearAmount', models.PositiveBigIntegerField(verbose_name='Last Year Amount')),
                ('consumed', models.PositiveBigIntegerField()),
                ('prevRemainingBalance', models.PositiveBigIntegerField(verbose_name='Prev Balance')),
                ('currentYearAmount', models.PositiveBigIntegerField(verbose_name='Current Year Amount')),
                ('crcAllocation', models.PositiveBigIntegerField(verbose_name='CRC Allocation')),
                ('pittyRepair', models.PositiveBigIntegerField(verbose_name='Pitty Repair')),
                ('totalExpenditure', models.PositiveBigIntegerField(verbose_name='Total Expenditure')),
                ('balance', models.PositiveBigIntegerField(verbose_name='Balance')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank')),
                ('chairman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chairman')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptcInfo', to='monthlyEntry.monthlyrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecordForProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.teacherproffqualification')),
                ('teacherEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proffessionalQualification', to='monthlyEntry.teachermonthlyentry')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecordForAcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.teacheraccadqualification')),
                ('teacherEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccademicQualification', to='monthlyEntry.teachermonthlyentry')),
            ],
        ),
    ]
