# Generated by Django 4.2 on 2023-11-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbuilding',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='monthlyEntry.monthlyrecord'),
        ),
    ]
