# Generated by Django 4.2 on 2023-09-29 04:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(default='-', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CHAIRMAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('contact', models.CharField(max_length=11, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(default='-', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CIRCLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Class Name')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'In-Active')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ITEM_CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True, verbose_name='Item Category')),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UCs', to='core.circle')),
            ],
            options={
                'verbose_name': 'Union Council',
                'verbose_name_plural': 'Union Councils',
                'db_table': 'Union_Council',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VCs', to='core.uc', verbose_name='Union Council')),
            ],
            options={
                'verbose_name': 'Village Council',
                'verbose_name_plural': 'Village Councils',
                'db_table': 'Village_Council',
            },
        ),
        migrations.CreateModel(
            name='STOCK_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Stock Item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.item_category')),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bps', models.CharField(choices=[('3', '3'), ('4', '4'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='Scale')),
            ],
            options={
                'ordering': ['bps'],
                'unique_together': {('name', 'bps')},
            },
        ),
    ]
